# Generated by Django 2.2.6 on 2019-10-26 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', martor.models.MartorField()),
                ('input', martor.models.MartorField()),
                ('output', martor.models.MartorField()),
                ('constraint', martor.models.MartorField()),
                ('time', models.PositiveSmallIntegerField()),
                ('memory', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='Unknown', editable=False, max_length=10)),
                ('host', models.PositiveSmallIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('UNE', 'Unknown Error'), ('WA', 'Wrong Answer'), ('RTE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('CTE', 'Compilation Error'), ('AC', 'Accepted')], default='PEN', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Problem')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', martor.models.MartorField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.TestCase')),
            ],
        ),
    ]
