# Generated by Django 2.2.7 on 2019-11-28 11:04

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('input_format', models.TextField(default=None)),
                ('output_format', models.TextField(default=None)),
                ('constraints', models.TextField(default=None)),
                ('time_limit', models.PositiveSmallIntegerField()),
                ('memory_limit', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('input', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='..\\..\\judge'), upload_to='TCIn')),
                ('output', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='..\\..\\judge'), upload_to='TCOut')),
                ('sample', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='..\\..\\judge'), upload_to='Submission')),
                ('language', models.CharField(default='UNKNOWN', editable=False, max_length=10)),
                ('host', models.PositiveSmallIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ACE', 'Abort Called Error'), ('CTE', 'Compilation Error'), ('MLE', 'Memory Limit Exceeded'), ('UNE', 'Unknown Error'), ('TLE', 'Time Limit Exceeded'), ('AC', 'Accepted'), ('RTE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('PEN', 'Pending')], default='PEN', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Problem')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.TestCase')),
            ],
        ),
    ]
