# Generated by Django 2.2.7 on 2019-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('WA', 'Wrong Answer'), ('ACE', 'Abort Called Error'), ('CTE', 'Compilation Error'), ('TLE', 'Time Limit Exceeded'), ('RTE', 'Runtime Error'), ('UNE', 'Unknown Error'), ('AC', 'Accepted'), ('PEN', 'Pending'), ('MLE', 'Memory Limit Exceeded')], default='PEN', max_length=3),
        ),
    ]
