# Generated by Django 2.2.7 on 2019-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20191128_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('MLE', 'Memory Limit Exceeded'), ('PEN', 'Pending'), ('WA', 'Wrong Answer'), ('UNE', 'Unknown Error'), ('RTE', 'Runtime Error'), ('CTE', 'Compilation Error'), ('ACE', 'Abort Called Error'), ('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded')], default='PEN', max_length=3),
        ),
    ]
