# Generated by Django 2.2.7 on 2019-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20191128_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('UNE', 'Unknown Error'), ('AC', 'Accepted'), ('RTE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('PEN', 'Pending'), ('ACE', 'Abort Called Error'), ('WA', 'Wrong Answer'), ('CTE', 'Compilation Error'), ('MLE', 'Memory Limit Exceeded')], default='PEN', max_length=3),
        ),
    ]
