# Generated by Django 2.2.7 on 2019-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20191128_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('RTE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('ACE', 'Abort Called Error'), ('MLE', 'Memory Limit Exceeded'), ('UNE', 'Unknown Error'), ('TLE', 'Time Limit Exceeded'), ('PEN', 'Pending'), ('CTE', 'Compilation Error'), ('AC', 'Accepted')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
