# Generated by Django 2.2.7 on 2019-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20191128_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('MLE', 'Memory Limit Exceeded'), ('PEN', 'Pending'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('ACE', 'Abort Called Error'), ('AC', 'Accepted'), ('RTE', 'Runtime Error'), ('UNE', 'Unknown Error'), ('CTE', 'Compilation Error')], default='PEN', max_length=3),
        ),
    ]
