# Generated by Django 2.2.7 on 2019-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20191128_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('TLE', 'Time Limit Exceeded'), ('UNE', 'Unknown Error'), ('CTE', 'Compilation Error'), ('RTE', 'Runtime Error'), ('PEN', 'Pending'), ('MLE', 'Memory Limit Exceeded'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('ACE', 'Abort Called Error')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
